In [1]:
import pandas as pd
import random
import numpy as np

random.seed(42)
np.random.seed(42)

print("Libraries Loaded")

Libraries Loaded

In [2]:
cities = ["Bangalore","Hyderabad","Chennai","Mumbai",
          "Pune","Delhi","Jaipur","Lucknow","Patna","Indore"]

cities

['Bangalore',
 'Hyderabad',
 'Chennai',
 'Mumbai',
 'Pune',
 'Delhi',
 'Jaipur',
 'Lucknow',
 'Patna',
 'Indore']

In [3]:
hubs = []

for i in range(25):
    hubs.append([
        i+1,
        random.choice(cities),
        "India",
        round(random.uniform(12,28),6),
        round(random.uniform(72,88),6),
        random.randint(500,2000),
        pd.Timestamp("2018-01-01") + pd.to_timedelta(random.randint(0,2000),"D")
    ])

hubs_df = pd.DataFrame(hubs,columns=[
    "hub_id","city","state","latitude","longitude","hub_capacity","hub_open_date"
])

hubs_df.head()

   hub_id       city  state   latitude  longitude  hub_capacity hub_open_date
0       1  Hyderabad  India  12.400172  76.400469           957    2018-10-13
1       2  Hyderabad  India  22.827192  86.274873           678    2021-04-24
2       3     Jaipur  India  12.508523  73.499124           976    2020-10-31
3       4     Indore  India  12.424576  75.181402          1830    2021-12-07
4       5      Patna  India  18.712317  79.187345          1069    2022-07-16

In [4]:
hubs_df.to_csv("hubs.csv",index=False)
print("Hubs file saved")

Hubs file saved

In [5]:
vehicles = ["Bike","Scooter","EV Bike"]

riders = []

for i in range(200):
    riders.append([
        i+1,
        f"Rider_{i+1}",
        round(random.uniform(0.5,8),1),
        random.choice(vehicles),
        random.randint(0,10),
        pd.Timestamp("2019-01-01") + pd.to_timedelta(random.randint(0,1500),"D"),
        random.randint(1,25)
    ])

riders_df = pd.DataFrame(riders,columns=[
    "rider_id","rider_name","experience_years",
    "vehicle_type","vehicle_age","joining_date","hub_id"
])

riders_df.head()

,rider_id,rider_name,experience_years,vehicle_type,vehicle_age,joining_date,hub_id
0,1,Rider_1,2.4,EV Bike,0,2022-10-25,24
1,2,Rider_2,1.4,EV Bike,4,2022-08-05,11
2,3,Rider_3,1.3,Scooter,2,2021-07-18,1
3,4,Rider_4,7.7,EV Bike,4,2021-10-22,25
4,5,Rider_5,1.8,Bike,10,2020-09-03,21

In [6]:
riders_df.to_csv("riders.csv",index=False)

In [7]:
customers = []

for i in range(3000):
    customers.append([
        i+1,
        random.choice(cities),
        random.randint(500000,600000),
        round(random.uniform(12,28),6),
        round(random.uniform(72,88),6),
        round(random.uniform(2.5,5.0),1)
    ])

customers_df = pd.DataFrame(customers,columns=[
    "customer_id","city","pincode",
    "latitude","longitude","customer_rating"
])

customers_df.head()

   customer_id       city  pincode   latitude  longitude  customer_rating
0            1     Jaipur   585175  13.285045  77.257049              4.2
1            2      Patna   549808  27.266233  82.028787              4.7
2            3    Lucknow   570912  12.574386  73.094732              4.1
3            4       Pune   529817  23.948262  78.943544              2.7
4            5  Hyderabad   558153  14.661837  76.791457              2.6

In [8]:
customers_df.to_csv("customers.csv",index=False)

In [9]:
weather_conditions = ["Clear","Rain","Storm","Fog"]

dates = pd.date_range(start="2024-01-01",periods=365)

weather_data = []

for date in dates:
    for city in cities:
        weather_data.append([
            date,
            city,
            random.choice(weather_conditions),
            random.randint(20,40),
            random.randint(40,95)
        ])

weather_df = pd.DataFrame(weather_data,columns=[
    "date","city","weather_condition","temperature","humidity"
])

weather_df.head()

        date       city weather_condition  temperature  humidity
0 2024-01-01  Bangalore             Storm           34        45
1 2024-01-01  Hyderabad              Rain           23        78
2 2024-01-01    Chennai             Clear           38        48
3 2024-01-01     Mumbai               Fog           35        75
4 2024-01-01       Pune             Storm           23        79

In [10]:
weather_df.to_csv("weather.csv",index=False)

In [11]:
delivery_status_options = ["Delivered","Failed","RTO"]
payment_types = ["COD","Prepaid"]

orders = []

for i in range(10000):

    order_time = pd.Timestamp("2024-01-01") + pd.to_timedelta(random.randint(0,365),"D")
    promised_time = order_time + pd.to_timedelta(random.randint(1,3),"D")
    actual_time = promised_time + pd.to_timedelta(random.randint(-1,3),"D")

    orders.append([
        i+1,
        random.randint(1,3000),
        random.randint(1,25),
        random.randint(1,200),
        order_time,
        promised_time,
        actual_time,
        random.choices(delivery_status_options,weights=[70,15,15])[0],
        random.choice(payment_types),
        round(random.uniform(200,5000),2)
    ])

orders_df = pd.DataFrame(orders,columns=[
    "order_id","customer_id","hub_id","rider_id",
    "order_time","promised_delivery_time","actual_delivery_time",
    "delivery_status","payment_type","order_value"
])

orders_df.head()

,order_id,customer_id,hub_id,rider_id,order_time,promised_delivery_time,actual_delivery_time,delivery_status,payment_type,order_value
0,1,685,11,45,2024-05-09,2024-05-11,2024-05-12,Failed,Prepaid,3750.05
1,2,2593,12,73,2024-02-08,2024-02-09,2024-02-09,Delivered,COD,4684.34
2,3,2447,23,158,2024-08-26,2024-08-29,2024-09-01,Delivered,Prepaid,2244.41
3,4,2336,20,57,2024-11-05,2024-11-07,2024-11-10,RTO,COD,1972.37
4,5,1773,15,90,2024-10-29,2024-11-01,2024-11-02,RTO,Prepaid,1199.39

In [12]:
orders_df.to_csv("orders.csv",index=False)

In [13]:
import os
os.getcwd()

'C:\\Users\\NARENDRA DAMERA'